/* Generated By:JavaCC: Do not edit this line. OdevConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OdevConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEMIC = 6;
  /** RegularExpression Id. */
  int ASSIGN = 7;
  /** RegularExpression Id. */
  int LBR = 8;
  /** RegularExpression Id. */
  int RBR = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int TRUE = 11;
  /** RegularExpression Id. */
  int FALSE = 12;
  /** RegularExpression Id. */
  int UNKNOWN = 13;
  /** RegularExpression Id. */
  int INPUT = 14;
  /** RegularExpression Id. */
  int OUTPUT = 15;
  /** RegularExpression Id. */
  int AND = 16;
  /** RegularExpression Id. */
  int OR = 17;
  /** RegularExpression Id. */
  int NOT = 18;
  /** RegularExpression Id. */
  int PROGRAM = 19;
  /** RegularExpression Id. */
  int MAINSECTION = 20;
  /** RegularExpression Id. */
  int ID = 21;
  /** RegularExpression Id. */
  int message = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"UNKNOWN\"",
    "\"INPUT\"",
    "\"OUTPUT\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"PROGRAM\"",
    "\"MAIN SECTION\"",
    "<ID>",
    "<message>",
    "\"DECLARATION SECTION\"",
    "\"INITIALIZATION SECTION\"",
  };

}
